'use client';

import { Loader2, Play, RefreshCw, Trash2 } from 'lucide-react';
import { BackendStatus } from '@/lib/types';

interface HeaderProps { status: BackendStatus | null; totalTraces: number; totalSpans: number; latestOp: string; isTriggering: boolean; isProgramRunning: boolean; onRunA: () => void; onRunB: () => void; onRefresh: () => void; onClear: () => void; onRunProgram: () => void; }

export function Header({ status, totalTraces, totalSpans, latestOp, isTriggering, isProgramRunning, onRunA, onRunB, onRefresh, onClear, onRunProgram }: HeaderProps) {
  return <header className="flex flex-wrap items-center justify-between gap-4 border-b border-obsidian-800 bg-obsidian-900 px-5 py-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-500">Zero-downtime physical prompting</p><h1 className="text-lg font-semibold tracking-tight text-white">Bidex <span className="text-slate-500">/</span> control room</h1></div><div className="hidden gap-5 font-mono text-[11px] text-slate-400 md:flex"><span>{status ? 'local backend' : 'demo mode'}</span><span>{totalTraces} traces</span><span>{totalSpans} spans</span><span className="max-w-36 truncate">{latestOp}</span></div><div className="flex items-center gap-2"><button disabled={isProgramRunning} onClick={onRunProgram} className="flex items-center gap-1.5 rounded-md bg-emerald-400 px-3 py-2 text-xs font-semibold text-obsidian-950 disabled:opacity-50">{isProgramRunning ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Play className="h-3.5 w-3.5 fill-current" />} {isProgramRunning ? 'Running...' : 'Run program'}</button><button disabled={isTriggering} onClick={onRunA} className="hidden items-center gap-1.5 rounded-md border border-obsidian-700 px-3 py-2 text-xs font-semibold text-slate-100 disabled:opacity-50"><Play className="h-3.5 w-3.5 fill-current" /> Run A</button><button disabled={isTriggering} onClick={onRunB} className="hidden items-center gap-1.5 rounded-md border border-obsidian-700 px-3 py-2 text-xs font-semibold text-slate-100 disabled:opacity-50"><Play className="h-3.5 w-3.5" /> Run B</button><button onClick={onRefresh} className="p-2 text-slate-400 hover:text-white" aria-label="Refresh"><RefreshCw className="h-4 w-4" /></button><button onClick={onClear} className="p-2 text-slate-500 hover:text-rose-300" aria-label="Clear traces"><Trash2 className="h-4 w-4" /></button></div></header>;
}
