'use client';

import { useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import { FilterType, TraceTree } from '@/lib/types';
import { formatDuration, formatTimestamp } from '@/lib/utils';

interface SidebarProps { traces: TraceTree[]; selectedTraceId: string | null; onSelectTrace: (id: string) => void; filter: FilterType; onFilterChange: (filter: FilterType) => void; isStreaming: boolean; utcTime: string; }

export function Sidebar({ traces, selectedTraceId, onSelectTrace, filter, onFilterChange, isStreaming, utcTime }: SidebarProps) {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => traces.filter((trace) => { const name = (trace.run_name || trace.root_name).toLowerCase(); const typeMatch = filter === 'all' || (filter === 'run_a' ? name.includes('run a') || name.includes('goto') : name.includes('run b') || name.includes('avoid') || name.includes('compose')); return typeMatch && `${name} ${trace.trace_id}`.includes(query.toLowerCase()); }), [traces, filter, query]);
  return <aside className="flex w-72 shrink-0 flex-col border-r border-obsidian-800 bg-obsidian-900"><div className="border-b border-obsidian-800 p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Runs</h2><span className="font-mono text-[11px] text-slate-500">{filtered.length}</span></div><div className="mt-3 flex gap-1">{(['all', 'run_a', 'run_b'] as FilterType[]).map((item) => <button key={item} onClick={() => onFilterChange(item)} className={`rounded px-2 py-1 text-[11px] ${filter === item ? 'bg-obsidian-750 text-white' : 'text-slate-500 hover:text-slate-200'}`}>{item === 'all' ? 'All' : item === 'run_a' ? 'Run A' : 'Run B'}</button>)}</div><label className="relative mt-3 block"><Search className="absolute left-2.5 top-2 h-3.5 w-3.5 text-slate-600" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search runs" className="w-full rounded-md border border-obsidian-800 bg-obsidian-950 py-1.5 pl-8 pr-2 text-xs text-slate-200 outline-none focus:border-obsidian-700" /></label></div><div className="min-h-0 flex-1 overflow-auto p-2">{filtered.length ? filtered.map((trace) => <button key={trace.trace_id} onClick={() => onSelectTrace(trace.trace_id)} className={`mb-1 w-full rounded-md px-3 py-2.5 text-left ${selectedTraceId === trace.trace_id ? 'bg-obsidian-800' : 'hover:bg-obsidian-850'}`}><div className="flex justify-between gap-2"><span className="truncate text-xs font-medium text-slate-200">{trace.run_name || trace.root_name}</span><span className="font-mono text-[10px] text-slate-500">{formatDuration(trace.total_duration_ms)}</span></div><p className="mt-1 font-mono text-[10px] text-slate-600">{formatTimestamp(trace.start_time_ns)} · {trace.span_count} steps</p></button>) : <p className="p-3 text-xs text-slate-600">No runs yet.</p>}</div><div className="border-t border-obsidian-800 px-4 py-3 font-mono text-[10px] text-slate-600">{isStreaming ? 'recording' : 'idle'} · {utcTime}</div></aside>;
}
